import type { Metadata } from 'next'
import WriterOnly from './WrittersOnly'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BLOGS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <WriterOnly>
      {children}
      </WriterOnly>
      
    </div>
  )
}
